services:
  - type: web
    name: video-translate-client
    runtime: static
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_SIGNALING_SERVER
        value: https://lgt-3.onrender.com

  - type: web
    name: video-translate-server
    runtime: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
